#ifndef _DEFINE_H_
#define _DEFINE_H_

#define APP_WIDTH		1024
#define APP_HEIGHT		600

#define H_SPACE			30
#define V_SPACE			5

#define STATIC_COM_LEFT			5
#define STATIC_COM_TOP			5
#define STATIC_COM_WIDTH		50
#define STATIC_COM_HEIGHT		30

#define COMBO_COM_LEFT			(STATIC_COM_LEFT + STATIC_COM_WIDTH)
#define COMBO_COM_TOP			STATIC_COM_TOP + 5
#define COMBO_COM_WIDTH			80
#define COMBO_COM_HEIGHT		20

#define BUTTON_CONNECT_LEFT		(COMBO_COM_LEFT + COMBO_COM_WIDTH + H_SPACE)
#define BUTTON_CONNECT_TOP		STATIC_COM_TOP
#define BUTTON_CONNECT_WIDTH	120
#define BUTTON_CONNECT_HEIGHT	STATIC_COM_HEIGHT



#define STATIC_BAUD_LEFT		5
#define STATIC_BAUD_TOP			(STATIC_COM_TOP + STATIC_COM_HEIGHT + V_SPACE)
#define STATIC_BAUD_WIDTH		STATIC_COM_WIDTH
#define STATIC_BAUD_HEIGHT		STATIC_COM_HEIGHT

#define COMBO_BAUD_LEFT			(STATIC_BAUD_LEFT + STATIC_BAUD_WIDTH)
#define COMBO_BAUD_TOP			STATIC_BAUD_TOP + 5
#define COMBO_BAUD_WIDTH		COMBO_COM_WIDTH
#define COMBO_BAUD_HEIGHT		20

#define BUTTON_AUTOCONNECT_LEFT		(COMBO_BAUD_LEFT + COMBO_BAUD_WIDTH + H_SPACE)
#define BUTTON_AUTOCONNECT_TOP		STATIC_BAUD_TOP
#define BUTTON_AUTOCONNECT_WIDTH	120
#define BUTTON_AUTOCONNECT_HEIGHT	STATIC_BAUD_HEIGHT




#define PICTURE_CONNECT_LEFT	(BUTTON_AUTOCONNECT_LEFT + BUTTON_AUTOCONNECT_WIDTH + H_SPACE)
#define PICTURE_CONNECT_WIDTH	32
#define PICTURE_CONNECT_HEIGHT	32
#define PICTURE_CONNECT_TOP		(BUTTON_CONNECT_TOP + (BUTTON_AUTOCONNECT_HEIGHT+BUTTON_CONNECT_HEIGHT+V_SPACE - PICTURE_CONNECT_HEIGHT)/2)

#define PICTURE_DISCONNECT_LEFT		PICTURE_CONNECT_LEFT
#define PICTURE_DISCONNECT_TOP		PICTURE_CONNECT_TOP
#define PICTURE_DISCONNECT_WIDTH	PICTURE_CONNECT_WIDTH
#define PICTURE_DISCONNECT_HEIGHT	PICTURE_CONNECT_HEIGHT

#define BUTTON_SETTAG_LEFT		5
#define BUTTON_SETTAG_TOP		(BUTTON_AUTOCONNECT_TOP + BUTTON_AUTOCONNECT_HEIGHT + V_SPACE)
#define BUTTON_SETTAG_WIDTH		BUTTON_CONNECT_WIDTH
#define BUTTON_SETTAG_HEIGHT	BUTTON_CONNECT_HEIGHT

#define BUTTON_SETROUTER_LEFT		(BUTTON_SETTAG_LEFT + BUTTON_SETTAG_WIDTH + H_SPACE)
#define BUTTON_SETROUTER_TOP		BUTTON_SETTAG_TOP
#define BUTTON_SETROUTER_WIDTH		BUTTON_CONNECT_WIDTH
#define BUTTON_SETROUTER_HEIGHT		BUTTON_CONNECT_HEIGHT

#define BUTTON_CLEAN_LEFT			(BUTTON_SETROUTER_LEFT + BUTTON_SETROUTER_WIDTH + H_SPACE)
#define BUTTON_CLEAN_TOP			BUTTON_SETTAG_TOP
#define BUTTON_CLEAN_WIDTH			BUTTON_SETTAG_WIDTH
#define BUTTON_CLEAN_HEIGHT			BUTTON_SETTAG_HEIGHT

#define LIST_INFO_LEFT				5
#define LIST_INFO_TOP				(BUTTON_SETROUTER_TOP + BUTTON_SETROUTER_HEIGHT + V_SPACE)
#define LIST_INFO_WIDTH				440
#define LIST_INFO_HEIGHT			450

#define DRAW_LEFT			460
#define DRAW_TOP			10
#define DRAW_WIDTH			550
#define DRAW_HEIGHT			550

#define BMP_ROUTER_WIDTH		80
#define BMP_ROUTER_HEIGHT		93	

#define DRAW_RADIUS		10

#define DRAW_TEXT_WIDTH		200
#define DRAW_TEXT_HEIGHT	2*DRAW_RADIUS



#define MAX_TAG_COUNT			5
#define MAX_ROUTER_COUNT		4

#define ID_LEN			8
#define NAME_LEN		16

struct TagInfo
{
	char ID[ID_LEN];
	char Name[NAME_LEN+2];
};

struct RouterInfo
{
	char ID[ID_LEN];
	char Name[NAME_LEN+2];
};

struct SaveInfo
{
	TagInfo tag[MAX_TAG_COUNT];
	RouterInfo router[MAX_ROUTER_COUNT];
};

struct ReceiveInfo
{
	bool ReceivData;			//是否接受到资料
	char TagId[ID_LEN];			//
	char RouterId[ID_LEN];		//保存最近的一个Router的ID
	char Single;				//保存最近的一个Router接受数据时候的信号强度
	char T_INT;
	char T_DEC;
	char H_INT;
	char H_DEC;
	short SingleToRouter[MAX_ROUTER_COUNT];		//保存Tag与4个指定Router的信号强度，从左上角开始，顺时针编号0,1,2,3
	DWORD FirstReceiveTime;		//第一次接受到数据的时间
};

struct ListShowInfo
{
	char TagId[ID_LEN];
	int index;
	char	LastDrawSingle;
	CPoint	LastDrawPoint;
	ReceiveInfo reciveinfo;
};

#define MAX_RECEIVEINFO_COUNT	200

#define MAX_RECEIVE_DATA_LEN	2048

#define CMD_NULL					0
#define CMD_SET_PANID				0x01
#define CMD_SET_DFAULT				0x02
#define CMD_GET_PANID 				0x03
#define CMD_GET_SHORTADDR			0x04
#define CMD_GET_BAUD				0x05
#define CMD_SET_BAUD				0x06
#define CMD_TEST_BAUD				0x07
#define CMD_SET_TO_COORDINATOR		0x08
#define CMD_SET_TO_ROUTER			0x09
#define CMD_GET_CHANNEL				0x10
#define CMD_SET_CHANNEL				0x11
#define CMD_GET_MACADDR				0x12
#define CMD_GET_TYPE				0x13
#define CMD_TEST_FIRMWARE			0x14
#define CMD_TEST_BAUD_DMATEK		0x15



#define SAVE_FILE_NAME	TEXT("ARF24.dat")
#define LOG_FILE_NAME	TEXT("Log.txt")



#endif